# 先拉取下节点的ansible setup信息，起到缓存效果，否则后续when 判断可能失败
- name: 缓存ansilbe setup信息
  setup: gather_subset=min
 
- name: apt更新缓存刷新
  apt: update_cache=yes cache_valid_time=72000
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

- name: apt安装 keepalived
  apt: name=keepalived state=latest
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

- name: yum安装 keepalived
  yum: name=keepalived state=latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: 创建keepalived配置目录
  file: name=/etc/keepalived state=directory

- name: 配置 keepalived 主节点
  template: src=keepalived-master.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: LB_ROLE == "master"

- name: 配置 keepalived 备节点
  template: src=keepalived-backup.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: LB_ROLE == "backup"

- name: 传送检测脚本
  template: src=check_apiserver.sh dest=/etc/keepalived
            owner=root mode=0755

- name: 开机启用keepalived服务
  shell: systemctl enable keepalived
  ignore_errors: true

- name: 重启keepalived服务
  shell: systemctl restart keepalived
